networks:
    syncthing4swarm:
        driver: overlay
        internal: true
volumes:
    syncthing-data:

services:
    syncthing4swarm:
        # https://github.com/sammonsempes/syncthing4swarm
        image: syncthing4swarm/syncthing4swarm:2.0.15
        volumes:
            - syncthing-data:/var/syncthing/data
        deploy:
            mode: global
        secrets:
            - stguiapikey
        environment:
            - STGUIAPIKEY_FILE=/run/secrets/stguiapikey
            - SYNCTHING_PORT=8384
            - SYNCTHING_FOLDER_PATH=/var/syncthing/data
            - PUID=0
            - PGID=0
        networks:
            - syncthing4swarm
secrets:
    stguiapikey:
        file: ./secret_stguiapikey
